apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: ak-gitops-test3
  project: defaultproject
spec:
  blueprint:
    name: minimal
    version: latest
  cloudCredentials: -dev-
  config:
    controlPlaneVersion: "1.26"
    features:
      enableComputeEnginePersistentDiskCSIDriver: true
    gcpProject: dev-382813
    location:
      config:
        zone: us-central1-a
      type: zonal
    network:
      access:
        config: null
        type: public
      enableVPCNativetraffic: true
      maxPodsPerNode: 110
      name: default
      subnetName: default
    nodePools:
    - machineConfig:
        bootDiskSize: 100
        bootDiskType: pd-standard
        imageType: COS_CONTAINERD
        machineType: e2-standard-4
      management:
        autoUpgrade: true
      name: default-nodepool
      nodeVersion: "1.26"
      size: 2
      upgradeSettings:
        blueGreenSettings:
          batchNodeCount: 2
          batchSoakDuration: 1s
          nodePoolSoakDuration: 3600s
        strategy: SURGE
        surgeSettings:
          maxSurge: 2
          maxUnavailable: 1
  type: gke
