apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: ak-gitops-test2
  project: defaultproject
spec:
  blueprint:
    name: minimal
    version: latest
  cloudCredentials: -dev-
  config:
    controlPlaneVersion: "1.27"
    features:
      enableComputeEnginePersistentDiskCSIDriver: true
    gcpProject: dev-382813
    location:
      config:
        zone: us-central1-a
      type: zonal
    network:
      access:
        config: null
        type: public
      enableVPCNativetraffic: true
      maxPodsPerNode: 110
      name: default
      subnetName: default
    nodePools:
    - machineConfig:
        bootDiskSize: 100
        bootDiskType: pd-standard
        imageType: COS_CONTAINERD
        machineType: e2-medium
        reservationAffinity:
          consumeReservationType: specific
          reservationName: ak-reservation-1
      management:
        autoUpgrade: true
      name: default-nodepool
      nodeVersion: "1.27"
      size: 2
      upgradeSettings:
        strategy: SURGE
        surgeSettings:
          maxSurge: 1
          maxUnavailable: 0
  type: gke
---
