apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: cli-v2spec-shared-vpc-rauto-520728558
  project: defaultproject
spec:
  blueprint:
    name: default-gke
    version: latest
  cloudCredentials: rauto_94551
  config:
    controlPlaneVersion: "1.24"
    features:
      enableComputeEnginePersistentDiskCSIDriver: true
    gcpProject: qa-automation-371111
    location:
      config:
        zone: us-central1-c
      defaultNodeLocations:
        enabled: true
        zones:
        - us-central1-c
      type: zonal
    network:
      access:
        config: null
        type: public
      enableVPCNativetraffic: true
      maxPodsPerNode: 110
      name: projects/dev-382813/global/networks/qaautomation-dev-vpc
      podSecondaryRangeName: qaautomation-sec-pods
      serviceSecondaryRangeName: qaautomation-sec-svc
      subnetName: projects/dev-382813/regions/us-central1/subnetworks/qaautomation-dev-sub1
    nodePools:
    - machineConfig:
        bootDiskSize: 100
        bootDiskType: pd-standard
        imageType: COS_CONTAINERD
        machineType: e2-standard-4
      name: phani-defaultnodepool
      nodeVersion: "1.24"
      size: 1
  type: gke
