apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: cli-with-sharing-rauto-652376865
  project: defaultproject
spec:
  blueprint:
    name: default-gke
    version: latest
  cloudCredentials: rauto_56227
  config:
    controlPlaneVersion: "1.24"
    gcpProject: qa-automation-371111
    location:
      config:
        zone: us-central1-a
      defaultNodeLocations:
        enabled: true
        zones:
        - us-central1-a
      type: zonal
    network:
      access:
        config: null
        type: public
      enableVPCNativetraffic: true
      maxPodsPerNode: 110
      name: default
      subnetName: default
    nodePools:
    - machineConfig:
        bootDiskSize: 100
        bootDiskType: pd-standard
        imageType: COS_CONTAINERD
        machineType: e2-standard-4
      name: phani-defaultnodepool
      nodeVersion: "1.24"
      size: 1
  sharing:
    enabled: true
    projects:
    - name: rauto-proj-gke-187873
    - name: rauto-proj-gke-7474419
  type: gke
