apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: rafay
  project: akshay
spec:
  blueprint:
    name: minimal
    version: latest
  cloudCredentials: -dev-
  config:
    controlPlaneVersion: "1.26"
    features:
      enableComputeEnginePersistentDiskCSIDriver: true
    gcpProject: dev-382813
    location:
      config:
        zone: us-central1-a
      type: zonal
    network:
      access:
        config: null
        type: public
      enableVPCNativetraffic: true
      maxPodsPerNode: 110
      name: default
      subnetName: default
    nodePools:
    - machineConfig:
        bootDiskSize: 100
        bootDiskType: pd-standard
        imageType: COS_CONTAINERD
        machineType: e2-standard-4
      name: default-nodepool
      nodeVersion: "1.26"
      size: 3
      upgradeSettings:
        config:
          maxSurge: 1
        strategy: SURGE
  type: gke
