apiVersion: infra.k8smgmt.io/v3
kind: FleetPlan
metadata:
  name: ak-new-prefernosche-test
  project: defaultproject
spec:
  agents:
  - name: fleet-agent
  fleet:
    kind: clusters
    labels:
      rafay.dev/clusterName: ak-fleet-target-5
    projects:
    - name: defaultproject
  operationWorkflow:
    operations:
    - action:
        controlPlaneUpgradeConfig:
          version: "1.29"
        name: upgrade
        type: controlPlaneUpgrade
      name: ak-operation
      prehooks:
      - containerConfig:
          arguments:
          - "60"
          commands:
          - sleep
          image: busybox
          runner:
            nodeSelector:
              key: value
            tolerations:
            - effect: PreferNoSchedule
              key: key
              operator: Equal
              value: value1
            type: cluster
        name: prehook
