apiVersion: infra.k8smgmt.io/v3
kind: FleetPlan
metadata:
  name: new-test1
  project: defaultproject
spec:
  fleet:
    kind: clusters
    labels:
      rafay.dev/clusterType: aws-eks
    projects:
    - name: defaultproject
  operationWorkflow:
    operations:
    - action:
        blueprintUpdateConfig:
          name: default
        name: asd
        type: blueprintUpdate
      name: newtest1
      prehooks:
      - containerConfig:
          arguments:
          - "60"
          commands:
          - sleep
          image: busybox
          runner:
            nodeSelector:
              key: value
            tolerations:
            - effect: NoExecute
              key: key
              operator: Equal
              tolerationSeconds: 3600
              value: value
            type: cluster
        name: prehook
