apiVersion: infra.k8smgmt.io/v3
kind: FleetPlan
metadata:
  name: ss
  project: defaultproject
spec:
  fleet:
    kind: clusters
    labels:
      rafay.dev/clusterName: ak-fleet-target4
    projects:
    - name: defaultproject
  operationWorkflow:
    operations:
    - action:
        blueprintUpdateConfig:
          name: default
        name: asd
        type: blueprintUpdate
      name: op1
      prehooks:
      - containerConfig:
          image: bitnami/kubectl:latest
          runner:
            nodeSelector:
              key: val
            tolerations:
            - effect: PreferNoSchedule
              key: key
              operator: Equal
              value: value
            type: cluster
        name: pre
